import numpy as np
from dataloaders.BaseDataset import BaseDataset


class BasePadChest(BaseDataset):
    def __init__(self, task='all', data_root='./data/padchest/', image_root='./data/padchest/images',
                 ann_file='annotations.json', **kwargs):
        super().__init__(task)
        self.data_root = data_root
        self.image_root = image_root
        self.ann_file = ann_file

    @staticmethod
    def get_all_class_names_ordered():
        """We consider all classes width depth <= 1 of the PadChest Tree
        https://github.com/auriml/Rx-thorax-automatic-captioning/blob/master/manual_review/trees_code.txt
        """
        return ['descendent aortic elongation', 'hilar congestion', 'infiltrates', 'bronchovascular markings',
                'endotracheal tube', 'normal', 'hilar enlargement', 'end on vessel', 'increased density',
                'chronic changes', 'interstitial pattern', 'round atelectasis', 'costochondral junction hypertrophy',
                'osteoporosis', 'abscess', 'right sided aortic arch', 'superior mediastinal enlargement',
                'total atelectasis', 'atelectasis', 'mass', 'hydropneumothorax', 'esophagic dilatation',
                'abnormal foreign body', 'non axial articular degenerative changes', 'rib fracture', 'gynecomastia',
                'pseudonodule', 'pleural plaques', 'surgery lung', 'vascular redistribution',
                'loculated fissural effusion', 'pleural mass', 'multiple nodules', 'fibrotic band',
                'segmental atelectasis', 'clavicle fracture', 'hemothorax', 'aortic aneurysm', 'pleural thickening',
                'artificial heart valve', 'sclerotic bone lesion', 'mediastinic lipomatosis',
                'artificial aortic heart valve', 'calcified adenopathy', 'bone cement', 'osteopenia',
                'pleural effusion', 'aortic atheromatosis', 'diaphragmatic eventration', 'electrical device',
                'calcified pleural thickening', 'calcified densities', 'adenopathy', 'volume loss', 'gastrostomy tube',
                'surgery heart', 'hyperinflated lung', 'soft tissue mass', 'nodule', 'atelectasis basal',
                'cardiomegaly', 'pectum carinatum', 'surgery humeral', 'pneumomediastinum', 'aortic elongation',
                'catheter', 'heart valve calcified', 'air trapping', 'bullas', 'tracheal shift', 'prosthesis',
                'fracture', 'mediastinal shift', 'external foreign body', 'central vascular redistribution',
                'lung vascular paucity', 'laminar atelectasis', 'pneumoperitoneo', 'bronchiectasis', 'unchanged',
                'pectum excavatum', 'Chilaiditi sign', 'dual chamber device', 'calcified fibroadenoma',
                'ascendent aortic elongation', 'hiatal hernia', 'air fluid level', 'blastic bone lesion',
                'humeral fracture', 'surgery neck', 'minor fissure thickening', 'apical pleural thickening',
                'vertebral degenerative changes', 'supra aortic elongation', 'vertebral fracture', 'nipple shadow',
                'lobar atelectasis', 'metal', 'subacromial space narrowing', 'thoracic cage deformation', 'azygos lobe',
                'vascular hilar enlargement', 'lytic bone lesion', 'surgery breast', 'breast mass',
                'azygoesophageal recess shift', 'hypoexpansion', 'pericardial effusion', 'NSG tube',
                'central venous catheter', 'dai', 'chest drain tube', 'calcified pleural plaques', 'cavitation',
                'scoliosis', 'nephrostomy tube', 'sternoclavicular junction hypertrophy', 'kyphosis',
                'artificial mitral heart valve', 'empyema', 'loculated pleural effusion', 'single chamber device',
                'double J stent', 'costophrenic angle blunting', 'granuloma', 'fissure thickening', 'surgery',
                'dextrocardia', 'pneumothorax', 'pulmonary mass', 'kerley lines', 'hemidiaphragm elevation',
                'mediastinal enlargement', 'mediastinal mass', 'cervical rib', 'obesity', 'cyst', 'flattened diaphragm',
                'major fissure thickening', 'aortic button enlargement', 'vertebral compression', 'calcified granuloma',
                'alveolar pattern', 'ventriculoperitoneal drain tube', 'pacemaker', 'subcutaneous emphysema',
                'axial hyperostosis', 'tracheostomy tube']

    def get_tasks(self):
        return ['all', 'root-level']

    def get_tree(self):
        if self.task == 'root-level':
            return {'normal': {'normal'}, 'unchanged': {'unchanged'}, 'obesity': {'obesity'},
                    'chronic changes': {'chronic changes'},
                    'calcified densities': {'calcified mediastinal adenopathy', 'calcified pleural thickening',
                                            'heart valve calcified', 'calcified pleural plaques', 'calcified densities',
                                            'calcified granuloma', 'calcified adenopathy', 'calcified fibroadenoma'},
                    'granuloma': {'calcified granuloma', 'granuloma'}, 'end on vessel': {'end on vessel'},
                    'adenopathy': {'adenopathy', 'calcified adenopathy'}, 'nodule': {'multiple nodules', 'nodule'},
                    'pseudonodule': {'nipple shadow', 'pseudonodule', 'end on vessel'}, 'abscess': {'abscess'},
                    'cyst': {'cyst'}, 'cavitation': {'cavitation'}, 'fibrotic band': {'fibrotic band'},
                    'volume loss': {'volume loss'}, 'hypoexpansion': {'hypoexpansion'}, 'bullas': {'bullas'},
                    'pneumothorax': {'hydropneumothorax', 'pneumothorax'}, 'pneumoperitoneo': {'pneumoperitoneo'},
                    'pneumomediastinum': {'pneumomediastinum'}, 'subcutaneous emphysema': {'subcutaneous emphysema'},
                    'hyperinflated lung': {'hyperinflated lung'}, 'flattened diaphragm': {'flattened diaphragm'},
                    'lung vascular paucity': {'lung vascular paucity'}, 'air trapping': {'air trapping'},
                    'bronchiectasis': {'bronchiectasis'},
                    'infiltrates': {'miliary opacities', 'consolidation', 'reticulonodular interstitial pattern',
                                    'ground glass pattern', 'reticular interstitial pattern', 'air bronchogram',
                                    'interstitial pattern', 'infiltrates', 'alveolar pattern'},
                    'bronchovascular markings': {'bronchovascular markings'}, 'air fluid level': {'air fluid level'},
                    'increased density': {'increased density'},
                    'atelectasis': {'laminar atelectasis', 'atelectasis basal', 'segmental atelectasis',
                                    'lobar atelectasis', 'total atelectasis', 'atelectasis', 'round atelectasis'},
                    'mediastinal shift': {'mediastinal shift'}, 'azygos lobe': {'azygos lobe'},
                    'fissure thickening': {'major fissure thickening', 'loculated fissural effusion',
                                           'fissure thickening', 'minor fissure thickening'},
                    'pleural thickening': {'calcified pleural thickening', 'apical pleural thickening',
                                           'pleural thickening'},
                    'pleural plaques': {'calcified pleural plaques', 'pleural plaques'},
                    'pleural effusion': {'hemothorax', 'empyema', 'pleural effusion', 'hydropneumothorax',
                                         'loculated fissural effusion', 'loculated pleural effusion'},
                    'pleural mass': {'pleural mass'}, 'costophrenic angle blunting': {'costophrenic angle blunting'},
                    'vascular redistribution': {'vascular redistribution', 'central vascular redistribution'},
                    'hilar enlargement': {'hilar enlargement', 'vascular hilar enlargement', 'adenopathy',
                                          'pulmonary artery enlargement'}, 'hilar congestion': {'hilar congestion'},
                    'cardiomegaly': {'cardiomegaly'}, 'pericardial effusion': {'pericardial effusion'},
                    'kerley lines': {'kerley lines'}, 'dextrocardia': {'dextrocardia'},
                    'right sided aortic arch': {'right sided aortic arch'},
                    'aortic atheromatosis': {'aortic atheromatosis'},
                    'aortic elongation': {'supra aortic elongation', 'aortic button enlargement',
                                          'ascendent aortic elongation', 'aortic elongation',
                                          'descendent aortic elongation'}, 'aortic aneurysm': {'aortic aneurysm'},
                    'mediastinal enlargement': {'hiatal hernia', 'mediastinal mass', 'superior mediastinal enlargement',
                                                'mediastinal enlargement', 'aortic aneurysm', 'goiter',
                                                'supra aortic elongation', 'ascendent aortic elongation',
                                                'descendent aortic elongation'}, 'tracheal shift': {'tracheal shift'},
                    'mass': {'pleural mass', 'mediastinal mass', 'breast mass', 'soft tissue mass', 'pulmonary mass',
                             'mass'}, 'esophagic dilatation': {'esophagic dilatation'},
                    'azygoesophageal recess shift': {'azygoesophageal recess shift'},
                    'mediastinic lipomatosis': {'mediastinic lipomatosis'},
                    'thoracic cage deformation': {'kyphosis', 'thoracic cage deformation', 'pectum carinatum',
                                                  'scoliosis', 'cervical rib', 'pectum excavatum'},
                    'vertebral degenerative changes': {'vertebral degenerative changes',
                                                       'vertebral anterior compression', 'vertebral compression'},
                    'lytic bone lesion': {'lytic bone lesion'},
                    'sclerotic bone lesion': {'sclerotic bone lesion', 'blastic bone lesion'},
                    'costochondral junction hypertrophy': {'costochondral junction hypertrophy'},
                    'sternoclavicular junction hypertrophy': {'sternoclavicular junction hypertrophy'},
                    'axial hyperostosis': {'axial hyperostosis'}, 'osteopenia': {'osteopenia'},
                    'osteoporosis': {'osteoporosis'},
                    'non axial articular degenerative changes': {'non axial articular degenerative changes'},
                    'subacromial space narrowing': {'subacromial space narrowing'},
                    'fracture': {'fracture', 'clavicle fracture', 'rib fracture', 'callus rib fracture',
                                 'vertebral fracture', 'humeral fracture'}, 'gynecomastia': {'gynecomastia'},
                    'hiatal hernia': {'hiatal hernia'}, 'Chilaiditi sign': {'Chilaiditi sign'},
                    'hemidiaphragm elevation': {'hemidiaphragm elevation'},
                    'diaphragmatic eventration': {'diaphragmatic eventration'},
                    'tracheostomy tube': {'tracheostomy tube'}, 'endotracheal tube': {'endotracheal tube'},
                    'NSG tube': {'NSG tube'}, 'chest drain tube': {'chest drain tube'},
                    'ventriculoperitoneal drain tube': {'ventriculoperitoneal drain tube'},
                    'gastrostomy tube': {'gastrostomy tube'}, 'nephrostomy tube': {'nephrostomy tube'},
                    'double J stent': {'double J stent'}, 'catheter': {'central venous catheter via umbilical vein',
                                                                       'central venous catheter via subclavian vein',
                                                                       'central venous catheter', 'catheter',
                                                                       'central venous catheter via jugular vein',
                                                                       'reservoir central venous catheter'},
                    'electrical device': {'pacemaker', 'single chamber device', 'electrical device',
                                          'dual chamber device', 'dai'},
                    'artificial heart valve': {'artificial heart valve', 'artificial mitral heart valve',
                                               'artificial aortic heart valve'},
                    'surgery': {'metal', 'osteosynthesis material', 'surgery humeral', 'surgery breast',
                                'aortic endoprosthesis', 'suture material', 'surgery heart', 'bone cement',
                                'mammary prosthesis', 'surgery neck', 'surgery lung', 'humeral prosthesis',
                                'sternotomy', 'prosthesis', 'mastectomy', 'endoprosthesis', 'surgery'},
                    'abnormal foreign body': {'abnormal foreign body'},
                    'external foreign body': {'external foreign body'}}



        elif self.task == 'all':
            return {'normal': {'normal'}, 'unchanged': {'unchanged'}, 'obesity': {'obesity'},
                    'chronic changes': {'chronic changes'}, 'calcified densities': {'calcified densities'},
                    'calcified granuloma': {'calcified granuloma'}, 'calcified adenopathy': {'calcified adenopathy'},
                    'calcified pleural thickening': {'calcified pleural thickening'},
                    'calcified pleural plaques': {'calcified pleural plaques'},
                    'heart valve calcified': {'heart valve calcified'},
                    'calcified fibroadenoma': {'calcified fibroadenoma'}, 'granuloma': {'granuloma'},
                    'end on vessel': {'end on vessel'}, 'adenopathy': {'adenopathy'}, 'nodule': {'nodule'},
                    'multiple nodules': {'multiple nodules'}, 'pseudonodule': {'pseudonodule'},
                    'nipple shadow': {'nipple shadow'}, 'abscess': {'abscess'}, 'cyst': {'cyst'},
                    'cavitation': {'cavitation'}, 'fibrotic band': {'fibrotic band'}, 'volume loss': {'volume loss'},
                    'hypoexpansion': {'hypoexpansion'}, 'bullas': {'bullas'}, 'pneumothorax': {'pneumothorax'},
                    'hydropneumothorax': {'hydropneumothorax'}, 'pneumoperitoneo': {'pneumoperitoneo'},
                    'pneumomediastinum': {'pneumomediastinum'}, 'subcutaneous emphysema': {'subcutaneous emphysema'},
                    'hyperinflated lung': {'hyperinflated lung'}, 'flattened diaphragm': {'flattened diaphragm'},
                    'lung vascular paucity': {'lung vascular paucity'}, 'air trapping': {'air trapping'},
                    'bronchiectasis': {'bronchiectasis'}, 'infiltrates': {'infiltrates'},
                    'interstitial pattern': {'reticular interstitial pattern', 'reticulonodular interstitial pattern',
                                             'ground glass pattern', 'miliary opacities', 'interstitial pattern'},
                    'alveolar pattern': {'alveolar pattern', 'air bronchogram', 'consolidation'},
                    'bronchovascular markings': {'bronchovascular markings'}, 'air fluid level': {'air fluid level'},
                    'increased density': {'increased density'}, 'atelectasis': {'atelectasis'},
                    'total atelectasis': {'total atelectasis'}, 'lobar atelectasis': {'lobar atelectasis'},
                    'segmental atelectasis': {'segmental atelectasis'}, 'laminar atelectasis': {'laminar atelectasis'},
                    'round atelectasis': {'round atelectasis'}, 'atelectasis basal': {'atelectasis basal'},
                    'mediastinal shift': {'mediastinal shift'}, 'azygos lobe': {'azygos lobe'},
                    'fissure thickening': {'fissure thickening'},
                    'minor fissure thickening': {'minor fissure thickening'},
                    'major fissure thickening': {'major fissure thickening'},
                    'loculated fissural effusion': {'loculated fissural effusion'},
                    'pleural thickening': {'pleural thickening'},
                    'apical pleural thickening': {'apical pleural thickening'}, 'pleural plaques': {'pleural plaques'},
                    'pleural effusion': {'pleural effusion'},
                    'loculated pleural effusion': {'loculated pleural effusion'}, 'empyema': {'empyema'},
                    'hemothorax': {'hemothorax'}, 'pleural mass': {'pleural mass'},
                    'costophrenic angle blunting': {'costophrenic angle blunting'},
                    'vascular redistribution': {'vascular redistribution'},
                    'central vascular redistribution': {'central vascular redistribution'},
                    'hilar enlargement': {'hilar enlargement'},
                    'vascular hilar enlargement': {'pulmonary artery enlargement', 'vascular hilar enlargement'},
                    'hilar congestion': {'hilar congestion'}, 'cardiomegaly': {'cardiomegaly'},
                    'pericardial effusion': {'pericardial effusion'}, 'kerley lines': {'kerley lines'},
                    'dextrocardia': {'dextrocardia'}, 'right sided aortic arch': {'right sided aortic arch'},
                    'aortic atheromatosis': {'aortic atheromatosis'}, 'aortic elongation': {'aortic elongation'},
                    'descendent aortic elongation': {'descendent aortic elongation'},
                    'ascendent aortic elongation': {'ascendent aortic elongation'},
                    'aortic button enlargement': {'aortic button enlargement'},
                    'supra aortic elongation': {'supra aortic elongation'}, 'aortic aneurysm': {'aortic aneurysm'},
                    'mediastinal enlargement': {'mediastinal enlargement'},
                    'superior mediastinal enlargement': {'supra aortic elongation', 'superior mediastinal enlargement',
                                                         'goiter'}, 'mediastinal mass': {'mediastinal mass'},
                    'hiatal hernia': {'hiatal hernia'}, 'tracheal shift': {'tracheal shift'}, 'mass': {'mass'},
                    'breast mass': {'breast mass'}, 'pulmonary mass': {'pulmonary mass'},
                    'soft tissue mass': {'soft tissue mass'}, 'esophagic dilatation': {'esophagic dilatation'},
                    'azygoesophageal recess shift': {'azygoesophageal recess shift'},
                    'mediastinic lipomatosis': {'mediastinic lipomatosis'},
                    'thoracic cage deformation': {'thoracic cage deformation'}, 'scoliosis': {'scoliosis'},
                    'kyphosis': {'kyphosis'}, 'pectum excavatum': {'pectum excavatum'},
                    'pectum carinatum': {'pectum carinatum'}, 'cervical rib': {'cervical rib'},
                    'vertebral degenerative changes': {'vertebral degenerative changes'},
                    'vertebral compression': {'vertebral anterior compression', 'vertebral compression'},
                    'lytic bone lesion': {'lytic bone lesion'}, 'sclerotic bone lesion': {'sclerotic bone lesion'},
                    'blastic bone lesion': {'blastic bone lesion'},
                    'costochondral junction hypertrophy': {'costochondral junction hypertrophy'},
                    'sternoclavicular junction hypertrophy': {'sternoclavicular junction hypertrophy'},
                    'axial hyperostosis': {'axial hyperostosis'}, 'osteopenia': {'osteopenia'},
                    'osteoporosis': {'osteoporosis'},
                    'non axial articular degenerative changes': {'non axial articular degenerative changes'},
                    'subacromial space narrowing': {'subacromial space narrowing'}, 'fracture': {'fracture'},
                    'clavicle fracture': {'clavicle fracture'}, 'humeral fracture': {'humeral fracture'},
                    'vertebral fracture': {'vertebral fracture'},
                    'rib fracture': {'rib fracture', 'callus rib fracture'}, 'gynecomastia': {'gynecomastia'},
                    'Chilaiditi sign': {'Chilaiditi sign'}, 'hemidiaphragm elevation': {'hemidiaphragm elevation'},
                    'diaphragmatic eventration': {'diaphragmatic eventration'},
                    'tracheostomy tube': {'tracheostomy tube'}, 'endotracheal tube': {'endotracheal tube'},
                    'NSG tube': {'NSG tube'}, 'chest drain tube': {'chest drain tube'},
                    'ventriculoperitoneal drain tube': {'ventriculoperitoneal drain tube'},
                    'gastrostomy tube': {'gastrostomy tube'}, 'nephrostomy tube': {'nephrostomy tube'},
                    'double J stent': {'double J stent'}, 'catheter': {'catheter'},
                    'central venous catheter': {'reservoir central venous catheter', 'central venous catheter',
                                                'central venous catheter via subclavian vein',
                                                'central venous catheter via jugular vein',
                                                'central venous catheter via umbilical vein'},
                    'electrical device': {'electrical device'}, 'dual chamber device': {'dual chamber device'},
                    'single chamber device': {'single chamber device'}, 'pacemaker': {'pacemaker'}, 'dai': {'dai'},
                    'artificial heart valve': {'artificial heart valve'},
                    'artificial mitral heart valve': {'artificial mitral heart valve'},
                    'artificial aortic heart valve': {'artificial aortic heart valve'}, 'surgery': {'surgery'},
                    'metal': {'sternotomy', 'metal', 'osteosynthesis material', 'suture material'},
                    'bone cement': {'bone cement'},
                    'prosthesis': {'humeral prosthesis', 'aortic endoprosthesis', 'prosthesis', 'mammary prosthesis',
                                   'endoprosthesis'}, 'surgery breast': {'mastectomy', 'surgery breast'},
                    'surgery neck': {'surgery neck'}, 'surgery lung': {'surgery lung'},
                    'surgery heart': {'surgery heart'}, 'surgery humeral': {'surgery humeral'},
                    'abnormal foreign body': {'abnormal foreign body'},
                    'external foreign body': {'external foreign body'}}

    def get_encoded_label(self, label):

        """
        Dataset specific label processing
        :param label: 1-D python list
        """
        label = np.array(label).astype(np.float)
        label[label < 0] = 0.0
        # print(self.print_label(label, self.get_all_class_names_ordered()))

        # If no label is specified, put No Finding
        if sum(label) == 0:
            label[self.pos_label_all['No Finding']] = 1.0

        # When task is binary we cant have No findings and Support Devices to coexist
        # This would return the label [1,1] according to the binary tree.
        if self.task == 'binary' \
                and (label[self.pos_label_all['Support Devices']] == 1.0) \
                and (label[self.pos_label_all['No Finding']] == 1.0):
            label[self.pos_label_all['Support Devices']] = 0.0
        return super().get_encoded_label(label)
