model:
    name: CheXbert
dataset:
    name: MimicDataset
    task: all
report:
    report_policy: impression
experiment:
    name: chexbert_mimic
    output_dir: embeddings/output/
    save_vectors: False
    do_split:
#        - train
        - val
        - test