model:
    name: CNNVec
    checkpoint: classifier/checkpoints/constrained1.0/best0.6788932415487947.pkl
#    checkpoint: classifier/checkpoints/my_model_constrained/best0.6354023763385523.pkl
dataset:
    name: MimicDataset
    task: all
    return_image: True
    image_root: data/mimic-cxr/
experiment:
    name: densenet169_mimic_six
    output_dir: embeddings/output/3.0
    save_vectors: False
    do_split:
        - val
        - test