model:
    name: Doc2vec
    to_train: True
    vector_size: 768
    epochs: 100
dataset:
    name: MimicDataset
    task: six
report:
    report_policy: impression
experiment:
    name: doc2vec_mimic
    output_dir: embeddings/output/
    save_vectors: False
    do_split:
        - val
        - test