model:
    name: Doc2vec
    checkpoint: embeddings/output/doc2vec_mimic/DBOW_vector768_window8_count15_epoch10_mimic.doc2vec
dataset:
    name: MimicDataset
    task: all
report:
    report_policy: impression
experiment:
    name: doc2vec_mimic_10
    output_dir: embeddings/output/
    save_vectors: False
    do_split:
        - val
        - test